# Generated by Django 5.2.15 on 2026-06-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('light', 'Luz'), ('door', 'Puerta'), ('lock', 'Cerradura')], max_length=20)),
                ('is_on', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_key', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=40)),
                ('command', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('ok', 'Correcto'), ('error', 'Error'), ('simulado', 'Simulado')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
