# Generated by Django 5.2.16 on 2026-07-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestate',
            name='kind',
            field=models.CharField(choices=[('light', 'Luz'), ('door', 'Puerta'), ('lock', 'Cerradura'), ('sensor', 'Sensor'), ('fan', 'Ventilador')], max_length=20),
        ),
    ]
