# Generated by Django 5.2.16 on 2026-07-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_devicestate_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestate',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
